# 4. Prepare the Data for Machine Learning Algorithms

In [70]:
import pandas as pd
import numpy as np
housing = pd.read_csv("housing_clean.csv")  # 불러오기

In [30]:
import pickle

# 저장된 strat_train_set 불러오기
with open('strat_train_set.pkl', 'rb') as f:
    strat_train_set = pickle.load(f)

housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()


In [31]:
housing = strat_train_set.drop("median_house_value", axis=1) # 훈련 세트에서 레이블을 제거
# axis=1은 컬럼 제거, axis=0이면 행 제거
housing_labels = strat_train_set["median_house_value"].copy()

## Data Cleaning

3가지 옵션:  
housing.dropna(subset=["total_bedrooms"]) # 옵션 1  null 값을 포함한 행 삭제  
housing.drop("total_bedrooms", axis=1) # 옵션 2  열 자체를 삭제  
median = housing["total_bedrooms"].median() # 옵션 3  열의 median을 계산하여, null 값을 그 중앙값으로 채우기  
housing["total_bedrooms"].fillna(median, inplace=True)  

각각의 옵션이 무엇을 하는지 보여주기 위해, null 값이 하나라도 포함된 행만 남긴 housing 데이터셋의 복사본을 만든다.  
그렇게 하면 각 옵션이 정확히 무엇을 하는지 시각적으로 쉽게 확인할 수 있다.

In [32]:
sample_incomplete_rows = housing[housing.isnull().any(axis=1)].head()
sample_incomplete_rows

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1606     -122.08     37.88                26.0       2947.0             NaN   
10915    -117.87     33.73                45.0       2264.0             NaN   
19150    -122.70     38.35                14.0       2313.0             NaN   
4186     -118.23     34.13                48.0       1308.0             NaN   
16885    -122.40     37.58                26.0       3281.0             NaN   

       population  households  median_income ocean_proximity  
1606        825.0       626.0         2.9330        NEAR BAY  
10915      1970.0       499.0         3.4193       <1H OCEAN  
19150       954.0       397.0         3.7813       <1H OCEAN  
4186        835.0       294.0         4.2891       <1H OCEAN  
16885      1145.0       480.0         6.3580      NEAR OCEAN

In [33]:
sample_incomplete_rows.dropna(subset=["total_bedrooms"])    # 옵션 1

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, ocean_proximity]
Index: []

In [34]:
sample_incomplete_rows.drop("total_bedrooms", axis=1)       # 옵션 2

longitude  latitude  housing_median_age  total_rooms  population  \
1606     -122.08     37.88                26.0       2947.0       825.0   
10915    -117.87     33.73                45.0       2264.0      1970.0   
19150    -122.70     38.35                14.0       2313.0       954.0   
4186     -118.23     34.13                48.0       1308.0       835.0   
16885    -122.40     37.58                26.0       3281.0      1145.0   

       households  median_income ocean_proximity  
1606        626.0         2.9330        NEAR BAY  
10915       499.0         3.4193       <1H OCEAN  
19150       397.0         3.7813       <1H OCEAN  
4186        294.0         4.2891       <1H OCEAN  
16885       480.0         6.3580      NEAR OCEAN

In [35]:
median = housing["total_bedrooms"].median()  # 옵션 3
sample_incomplete_rows["total_bedrooms"] = sample_incomplete_rows["total_bedrooms"].fillna(median)

In [36]:
sample_incomplete_rows

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1606     -122.08     37.88                26.0       2947.0           433.0   
10915    -117.87     33.73                45.0       2264.0           433.0   
19150    -122.70     38.35                14.0       2313.0           433.0   
4186     -118.23     34.13                48.0       1308.0           433.0   
16885    -122.40     37.58                26.0       3281.0           433.0   

       population  households  median_income ocean_proximity  
1606        825.0       626.0         2.9330        NEAR BAY  
10915      1970.0       499.0         3.4193       <1H OCEAN  
19150       954.0       397.0         3.7813       <1H OCEAN  
4186        835.0       294.0         4.2891       <1H OCEAN  
16885      1145.0       480.0         6.3580      NEAR OCEAN

In [37]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")

In [38]:
housing_num = housing.drop("ocean_proximity", axis=1)  
# 또는: housing_num = housing.select_dtypes(include=[np.number]),숫자형 데이터만 선택

In [39]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [40]:
imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [41]:
housing_num.median().values

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [46]:
X = imputer.transform(housing_num)
# imputer 객체를 사용하여 housing_num의 결측치를 대체

In [47]:
housing_tr = pd.DataFrame(X, columns=housing_num.columns,
                          index=housing.index)
# X 데이터를 DataFrame으로 변환, 원본 housing_num의 컬럼명과 인덱스를 그대로 유지

In [48]:
housing_tr.loc[sample_incomplete_rows.index.values]
# sample_incomplete_rows의 인덱스를 사용하여 결측치가 있던 행들만 추출

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1606     -122.08     37.88                26.0       2947.0           433.0   
10915    -117.87     33.73                45.0       2264.0           433.0   
19150    -122.70     38.35                14.0       2313.0           433.0   
4186     -118.23     34.13                48.0       1308.0           433.0   
16885    -122.40     37.58                26.0       3281.0           433.0   

       population  households  median_income  
1606        825.0       626.0         2.9330  
10915      1970.0       499.0         3.4193  
19150       954.0       397.0         3.7813  
4186        835.0       294.0         4.2891  
16885      1145.0       480.0         6.3580

In [52]:
imputer.strategy # 결측치 무엇으로 채우나?

'median'

In [55]:
housing_tr = pd.DataFrame(X, columns=housing_num.columns,
                          index=housing_num.index)
# X 데이터를 DataFrame으로 변환, 원본 housing_num의 컬럼명과 인덱스를 그대로 유지
# -> 결측치가 처리된 데이터는 원본 데이터와 같은 구조를 유지

In [51]:
housing_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   

       population  households  median_income  
12655      2237.0       706.0         2.1736  
15502      2015.0       768.0         6.3373  
2908        667.0       300.0         2.8750  
14053       898.0       483.0         2.2264  
20496      1837.0       580.0         4.4964

## Handling Text and Categorical Attributes

In [56]:
housing_cat = housing[["ocean_proximity"]]
housing_cat.head(10)

ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN
1481         NEAR BAY
18125       <1H OCEAN
5830        <1H OCEAN
17989       <1H OCEAN
4861        <1H OCEAN

In [59]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat) # "ocean_proximity" 컬럼만 포함하는 새로운 데이터프레임
housing_cat_encoded[:10]

array([[1.],
       [4.],
       [1.],
       [4.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [61]:
ordinal_encoder.categories_ # OrdinalEncoder 객체에서 카테고리형 변수의 각 고유 값 목록을 반환

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [62]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16512 stored elements and shape (16512, 5)>

In [63]:
housing_cat_1hot.toarray()
# 기본적으로 OneHotEncoder 클래스는 희소 배열을 반환하지만,  
# 필요한 경우 toarray() 메서드를 호출하여 이를 밀집 배열로 변환할 수 있음

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(16512, 5))

In [67]:
# OneHotEncoder를 생성할 때 sparse_output=False를 설정할 수 있다
cat_encoder = OneHotEncoder(sparse_output=False) # 예전에는 sparse=False 사용!
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(16512, 5))

In [68]:
cat_encoder.categories_


[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

## Custom Transformers

In [93]:
import pickle
from sklearn.base import BaseEstimator, TransformerMixin  # scikit-learn에서 BaseEstimator와 TransformerMixin을 임포트

# 각 컬럼의 인덱스를 변수로 설정
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room=True):  # 생성자에서 add_bedrooms_per_room 인자를 받음
        self.add_bedrooms_per_room = add_bedrooms_per_room  # 기본값 True로 설정

    def fit(self, X, y=None):
        return self  # fit 메서드는 변환할 데이터가 없으므로 그대로 반환

    def transform(self, X):
        # 각 특성들을 계산하여 새로운 특성 추가
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]  # 가구당 방 수
        population_per_household = X[:, population_ix] / X[:, households_ix]  # 가구당 인구 수
        if self.add_bedrooms_per_room:
            # add_bedrooms_per_room이 True일 경우, 추가 특성: 방당 침실 수
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]  
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]  # 새로운 특성 포함하여 반환
        else:
            return np.c_[X, rooms_per_household, population_per_household]  # 추가 특성만 포함하여 반환

# CombinedAttributesAdder 클래스를 이용해 인스턴스를 만들고, add_bedrooms_per_room을 False로 설정
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)

# housing 데이터를 변환하여 새로운 특성을 추가한 결과를 housing_extra_attribs에 저장
housing_extra_attribs = attr_adder.transform(housing.values)

# pickle로 CombinedAttributesAdder 객체 저장(다른 노트북에서 쓰기 위함)
with open('combined_attributes_adder.pkl', 'wb') as f:
    pickle.dump(attr_adder, f)


In [74]:
# 간결성과 명확성을 위해 인덱스(3, 4, 5, 6)를 하드코딩했지만, 
# 다음과 같이 동적으로 가져오는 것이 훨씬 더 깔끔할 것이다
col_names = "total_rooms", "total_bedrooms", "population", "households"
rooms_ix, bedrooms_ix, population_ix, households_ix = [
    housing.columns.get_loc(c) for c in col_names] # get the column indices

In [75]:
# housing_extra_attribs는 NumPy 배열이므로 열 이름이 손실(Scikit-Learn 문제)
# DataFrame 복구
housing_extra_attribs = pd.DataFrame(
    housing_extra_attribs,
    columns=list(housing.columns)+["rooms_per_household", "population_per_household"],
    index=housing.index)
housing_extra_attribs.head()

longitude latitude housing_median_age total_rooms total_bedrooms population  \
0   -121.46    38.52               29.0      3873.0          797.0     2237.0   
1   -117.23    33.09                7.0      5320.0          855.0     2015.0   
2   -119.04    35.37               44.0      1618.0          310.0      667.0   
3   -117.13    32.75               24.0      1877.0          519.0      898.0   
4    -118.7    34.28               27.0      3536.0          646.0     1837.0   

  households median_income ocean_proximity rooms_per_household  \
0      706.0        2.1736          INLAND            5.485836   
1      768.0        6.3373      NEAR OCEAN            6.927083   
2      300.0         2.875          INLAND            5.393333   
3      483.0        2.2264      NEAR OCEAN            3.886128   
4      580.0        4.4964       <1H OCEAN            6.096552   

  population_per_household  
0                 3.168555  
1                 2.623698  
2                 2.223333  
3                 1.859213  
4                 3.167241

## Transformation Pipelines

In [76]:
# pipeline 빌드
from sklearn.pipeline import Pipeline  # scikit-learn에서 Pipeline을 임포트
from sklearn.preprocessing import StandardScaler  # StandardScaler를 임포트

# 숫자형 데이터를 위한 파이프라인 정의
num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),  # 결측치는 중앙값으로 대체
        ('attribs_adder', CombinedAttributesAdder()),  # 새로운 특성(가구당 방 수, 인구 수 등) 추가
        ('std_scaler', StandardScaler()),  # 데이터 표준화 (평균 0, 분산 1)
    ])

# housing_num 데이터에 대해 파이프라인을 적용하여 변환된 데이터 얻기
housing_num_tr = num_pipeline.fit_transform(housing_num)


In [77]:
housing_num_tr

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.01739526,
         0.00622264, -0.12112176],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.56925554,
        -0.04081077, -0.81086696],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.01802432,
        -0.07537122, -0.33827252],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.5092404 ,
        -0.03743619,  0.32286937],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.32814891,
        -0.05915604, -0.45702273],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.01407228,
         0.00657083, -0.12169672]], shape=(16512, 11))

In [78]:
from sklearn.compose import ColumnTransformer  # ColumnTransformer를 임포트

# 숫자형 및 범주형 속성 리스트 정의
num_attribs = list(housing_num)  # 숫자형 속성 목록 (housing_num의 모든 컬럼 이름)
cat_attribs = ["ocean_proximity"]  # 범주형 속성 목록

# 전체 파이프라인 정의
full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),  # 숫자형 데이터는 num_pipeline을 적용
        ("cat", OneHotEncoder(), cat_attribs),  # 범주형 데이터는 OneHotEncoder를 적용
    ])

# housing 데이터에 대해 전체 파이프라인을 적용하여 변환된 데이터 얻기
housing_prepared = full_pipeline.fit_transform(housing)


In [79]:
housing_prepared

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]], shape=(16512, 16))

In [80]:
housing_prepared.shape

(16512, 16)

In [81]:
# DataFrameSelector 변환기(Pandas DataFrame 열의 하위 집합만 선택)와 
# FeatureUnion을 기반으로 한 기존 솔루션
from sklearn.base import BaseEstimator, TransformerMixin

# Create a class to select numerical or categorical columns 
class OldDataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [85]:
# 모든 구성 요소를 숫자형 및 범주형 기능을 모두 전처리하는 큰 파이프라인으로 결합

# 숫자형 및 범주형 속성 리스트 정의
num_attribs = list(housing_num)  # 숫자형 속성 목록 (housing_num의 모든 컬럼 이름)
cat_attribs = ["ocean_proximity"]  # 범주형 속성 목록

# 숫자형 데이터 처리 파이프라인 정의
old_num_pipeline = Pipeline([
        ('selector', OldDataFrameSelector(num_attribs)),  # 숫자형 속성 선택 (OldDataFrameSelector는 사용자 정의 클래스일 가능성 있음)
        ('imputer', SimpleImputer(strategy="median")),  # 결측치를 중앙값으로 대체
        ('attribs_adder', CombinedAttributesAdder()),  # 새로운 특성(가구당 방 수, 인구 수 등) 추가
        ('std_scaler', StandardScaler()),  # 데이터 표준화 (평균 0, 분산 1)
    ])

# 범주형 데이터 처리 파이프라인 정의
old_cat_pipeline = Pipeline([
        ('selector', OldDataFrameSelector(cat_attribs)),  # 범주형 속성 선택 (OldDataFrameSelector는 사용자 정의 클래스일 가능성 있음)
        ('cat_encoder', OneHotEncoder(sparse_output=False)),  # 범주형 데이터는 OneHotEncoder로 변환, sparse_output=False는 희소 행렬 대신 밀집 행렬 반환
    ])


In [86]:
from sklearn.pipeline import FeatureUnion  # FeatureUnion을 임포트

# 숫자형 데이터 처리 파이프라인과 범주형 데이터 처리 파이프라인을 합치는 FeatureUnion 정의
old_full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", old_num_pipeline),  # 숫자형 데이터 처리 파이프라인을 "num_pipeline"으로 추가
        ("cat_pipeline", old_cat_pipeline),  # 범주형 데이터 처리 파이프라인을 "cat_pipeline"으로 추가
    ])

In [87]:
# 전체 파이프라인을 사용하여 housing 데이터를 변환하고, 변환된 데이터를 old_housing_prepared에 저장
old_housing_prepared = old_full_pipeline.fit_transform(housing)

# 변환된 데이터 출력 (변환된 housing 데이터 확인)
old_housing_prepared

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]], shape=(16512, 16))

In [89]:
# 결과는 ColumnTransformer와 동일
np.allclose(housing_prepared, old_housing_prepared)

True

In [90]:
import pickle

# full_pipeline을 pickle로 저장
with open('full_pipeline.pkl', 'wb') as f:
    pickle.dump(full_pipeline, f)


In [38]:
import joblib
housing_prepared = joblib.load("data/housing_prepared.pkl")
housing_labels = joblib.load("data/housing_labels.pkl")
full_pipeline = joblib.load("models/full_pipeline.pkl")

In [13]:
from sklearn.linear_model import LinearRegression  # 선형 회귀 모델 임포트

lin_reg = LinearRegression()  # 모델 객체 생성
lin_reg.fit(housing_prepared, housing_labels)  # 훈련 데이터로 모델 학습

LinearRegression()

In [14]:
# 예측 테스트 (5개 샘플)

some_data = housing.iloc[:5]  # 원본 데이터에서 일부 샘플 추출
some_labels = housing_labels.iloc[:5]  # 실제 값 추출
some_data_prepared = full_pipeline.transform(some_data)  # 전처리 적용

print("Predictions:", lin_reg.predict(some_data_prepared))  # 예측값 출력
print("Labels:", list(some_labels))  # 실제값 출력

Predictions: [ 85657.90192014 305492.60737488 152056.46122456 186095.70946094
 244550.67966089]
Labels: [72100.0, 279600.0, 82700.0, 112500.0, 238300.0]


In [15]:
# RMSE 계산 (훈련 세트 기준)
from sklearn.metrics import mean_squared_error  # RMSE 계산용 함수

housing_predictions = lin_reg.predict(housing_prepared)  # 전체 예측
lin_mse = mean_squared_error(housing_labels, housing_predictions)  # MSE 계산
lin_rmse = np.sqrt(lin_mse)  # RMSE 계산

In [16]:
# 결정 트리 모델 훈련
from sklearn.tree import DecisionTreeRegressor  

tree_reg = DecisionTreeRegressor()
tree_reg.fit(housing_prepared, housing_labels)  # 학습

DecisionTreeRegressor()

In [17]:
# RMSE 계산 (훈련 세트 기준, 과적합 여부 확인)
housing_predictions = tree_reg.predict(housing_prepared)
tree_mse = mean_squared_error(housing_labels, housing_predictions)
tree_rmse = np.sqrt(tree_mse)  # 훈련 데이터에 대해 RMSE가 0일 수도 있음 → 과적합 신호

In [18]:
# 교차 검증 (결정 트리)
from sklearn.model_selection import cross_val_score  # 교차 검증 함수

scores = cross_val_score(tree_reg, housing_prepared, housing_labels,
                         scoring="neg_mean_squared_error", cv=10)  # 10겹 교차검증
rmse_scores = np.sqrt(-scores)  # 점수가 음수이므로 반전 후 제곱근 계산

In [19]:
# 점수 출력 함수
def display_scores(scores):  # 점수 리스트를 보기 좋게 출력
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

display_scores(rmse_scores)

Scores: [72501.64212996 71513.40218484 67830.54919907 71883.14883739
 69018.2726938  76111.58157257 71451.05987091 73682.5472033
 66976.23403519 70848.44973403]
Mean: 71181.68874610616
Standard deviation: 2582.2946569025576


In [20]:
# 교차 검증 (선형 회귀 비교)
lin_scores = cross_val_score(lin_reg, housing_prepared, housing_labels,
                             scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [71762.76364394 64114.99166359 67771.17124356 68635.19072082
 66846.14089488 72528.03725385 73997.08050233 68802.33629334
 66443.28836884 70139.79923956]
Mean: 69104.07998247063
Standard deviation: 2880.3282098180666


In [21]:
# 랜덤 포레스트 훈련 및 평가
from sklearn.ensemble import RandomForestRegressor  # 랜덤 포레스트 임포트

forest_reg = RandomForestRegressor()
forest_reg.fit(housing_prepared, housing_labels)  # 학습

forest_scores = cross_val_score(forest_reg, housing_prepared, housing_labels,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores: [51314.22213553 48933.25747258 46921.87189441 51649.30898705
 47600.76141668 51553.51720848 52409.02769873 49429.45814488
 48572.32898066 53861.81812521]
Mean: 50224.557206421174
Standard deviation: 2140.2460267705574


In [22]:
# 모델 저장 및 재사용
import joblib  # 대용량 모델 저장에 적합한 라이브러리

joblib.dump(forest_reg, "forest_model.pkl")  # 모델 저장
model_loaded = joblib.load("forest_model.pkl")  # 저장된 모델 불러오기


In [35]:
joblib.dump(lin_reg, "models/lin_reg.pkl")

['models/lin_reg.pkl']

In [36]:
import joblib
housing_prepared = joblib.load("data/housing_prepared.pkl")
housing_labels = joblib.load("data/housing_labels.pkl")

In [31]:

from sklearn.model_selection import GridSearchCV  # 하이퍼파라미터 튜닝을 위한 GridSearchCV 임포트
from sklearn.ensemble import RandomForestRegressor  # 랜덤 포레스트 회귀 모델 임포트

param_grid = [  # 탐색할 하이퍼파라미터 조합 정의
    {'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
    {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
]

forest_reg = RandomForestRegressor()  # 모델 객체 생성

grid_search = GridSearchCV(forest_reg, param_grid, cv=5,  # 그리드 탐색 객체 생성
                           scoring='neg_mean_squared_error',
                           return_train_score=True)

grid_search.fit(housing_prepared, housing_labels)  # 전체 훈련 세트로 학습 및 교차 검증

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             return_train_score=True, scoring='neg_mean_squared_error')

In [24]:
grid_search.best_params_  # 가장 좋은 하이퍼파라미터 조합 출력

{'max_features': 8, 'n_estimators': 30}

In [25]:
grid_search.best_estimator_  # 가장 성능이 좋은 모델 출력

RandomForestRegressor(max_features=8, n_estimators=30)

In [26]:
cvres = grid_search.cv_results_  # 교차 검증 결과 저장
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)  # RMSE와 하이퍼파라미터 조합 출력

64694.09167288166 {'max_features': 2, 'n_estimators': 3}
55164.88624325165 {'max_features': 2, 'n_estimators': 10}
52551.38765595925 {'max_features': 2, 'n_estimators': 30}
60388.731146036764 {'max_features': 4, 'n_estimators': 3}
53267.37802899572 {'max_features': 4, 'n_estimators': 10}
50207.50084450273 {'max_features': 4, 'n_estimators': 30}
59805.319690099546 {'max_features': 6, 'n_estimators': 3}
52377.60068584532 {'max_features': 6, 'n_estimators': 10}
50125.15542823475 {'max_features': 6, 'n_estimators': 30}
57755.02333209064 {'max_features': 8, 'n_estimators': 3}
52331.65182011444 {'max_features': 8, 'n_estimators': 10}
50109.42823492966 {'max_features': 8, 'n_estimators': 30}
62191.866890750294 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
54309.763829849544 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
60014.37816524238 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
52903.33724230673 {'bootstrap': False, 'max_features': 3, 'n_estimators'

In [27]:
feature_importances = grid_search.best_estimator_.feature_importances_  # 특성 중요도 추출

In [28]:
extra_attribs = ["rooms_per_hhold", "pop_per_hhold", "bedrooms_per_room"]  # 파생 변수 이름
cat_one_hot_attribs = list(cat_encoder.get_feature_names_out())  # 원-핫 인코딩된 범주형 변수 이름
attributes = num_attribs + extra_attribs + cat_one_hot_attribs  # 전체 특성 이름 합치기

In [29]:
sorted(zip(feature_importances, attributes), reverse=True)  # 특성 중요도 내림차순 정렬

[(np.float64(0.34213281602836687), 'median_income'),
 (np.float64(0.15558810299896655), 'ocean_proximity_INLAND'),
 (np.float64(0.11607402344039748), 'pop_per_hhold'),
 (np.float64(0.07590574708074133), 'bedrooms_per_room'),
 (np.float64(0.06727026530557186), 'longitude'),
 (np.float64(0.06477306726350168), 'latitude'),
 (np.float64(0.05902832413253498), 'rooms_per_hhold'),
 (np.float64(0.0429404779582283), 'housing_median_age'),
 (np.float64(0.01534387031122192), 'total_rooms'),
 (np.float64(0.014825442172739667), 'total_bedrooms'),
 (np.float64(0.014780045886326495), 'population'),
 (np.float64(0.014494803040373677), 'households'),
 (np.float64(0.011120000400319432), 'ocean_proximity_<1H OCEAN'),
 (np.float64(0.0029494573560954864), 'ocean_proximity_NEAR OCEAN'),
 (np.float64(0.002710684510062972), 'ocean_proximity_NEAR BAY'),
 (np.float64(6.287211455126793e-05), 'ocean_proximity_ISLAND')]

In [30]:
from sklearn.metrics import mean_squared_error  # RMSE 계산을 위한 모듈 임포트

final_model = grid_search.best_estimator_  # 최종 모델 지정

X_test = strat_test_set.drop("median_house_value", axis=1)  # 테스트 입력 특성
y_test = strat_test_set["median_house_value"].copy()  # 테스트 타깃 레이블

X_test_prepared = full_pipeline.transform(X_test)  # 전처리 파이프라인 적용
final_predictions = final_model.predict(X_test_prepared)  # 예측 수행

final_mse = mean_squared_error(y_test, final_predictions)  # MSE 계산
final_rmse = np.sqrt(final_mse)  # RMSE 계산
print(final_rmse)  # RMSE 출력

47800.95305004226


In [37]:
joblib.dump(grid_search, "models/grid_search.pkl")

['models/grid_search.pkl']

In [95]:
import pickle

# housing_prepared 데이터를 pickle로 저장
with open('housing_prepared.pkl', 'wb') as f:
    pickle.dump(housing_prepared, f)
