[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/0xInode/AI-study-notes/blob/main/math/linear_algebra/01_vectors_and_matrices_exercise.ipynb)


# 01. Vectors and Matrices - Exercise

벡터와 행렬의 기본 개념 실습용

In [1]:
import numpy as np

In [3]:
# 벡터 생성
v1 = np.array([1, 2])
v2 = np.array([3, 4])

print("v1 =", v1)
print("v2 =", v2)


v1 = [1 2]
v2 = [3 4]


In [4]:
# 벡터 덧셈 및 스칼라 곱
print("v1 + v2 =", v1 + v2)
print("3 * v1 =", 3 * v1)


v1 + v2 = [4 6]
3 * v1 = [3 6]


In [5]:
# 행렬 생성
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A =\n", A)
print("B =\n", B)


A =
 [[1 2]
 [3 4]]
B =
 [[5 6]
 [7 8]]


In [6]:
# 행렬-벡터 곱
result = A @ v1
print("A @ v1 =", result)

A @ v1 = [ 5 11]


In [7]:
# 행렬 곱
C = A @ B
print("A @ B =\n", C)

A @ B =
 [[19 22]
 [43 50]]


In [8]:
# 전치
print("A^T =\n", A.T)

A^T =
 [[1 3]
 [2 4]]
